# Testing fastCPH

In [1]:
import numpy

In [2]:
import sklearn

In [3]:
import survhive

In [4]:
X, y = survhive.load_test_data()
X.shape, y.shape
min(survhive.get_time(y))

125.0

In [5]:
#my_data='gbsg2'
#my_data_df=survhive.datasets.get_data(my_data)
seed=2401

#X, y= my_data_df.get_X_y()
#X.shape, y.shape

### Generate a (stratified) train-test split and Scale the features (only) 

First do the stratified splitting THEN do scaling, parameterized on X_train set ONLY 

In [6]:
from sklearn.preprocessing import StandardScaler, RobustScaler

In [7]:
X_train, X_test, y_train, y_test = survhive.survival_train_test_split(X, y,rng_seed=2311)

In [8]:
scaler = StandardScaler().fit(X_train)
[X_train, X_test] = [ scaler.transform(_) for _ in  [X_train, X_test] ]
X_train.shape, X_test.shape

((148, 84), (50, 84))

In [9]:
#X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y)

balanced partitioning OK. Robst scaler damages the performance of DSM A LOT.
maybe did something wrong. It is standard scaler for now.

In [10]:
survhive.get_indicator(y).sum(), survhive.get_indicator(y_train).sum(), survhive.get_indicator(y_test).sum(),


(51, 38, 13)

In [11]:
splitter = survhive.survival_crossval_splitter(X_train,y_train,n_splits=3, n_repeats=2,rng_seed=2309)
print([ (survhive.get_indicator(y_train[_[1]]).sum()) for _ in splitter])

[13, 12, 13, 13, 12, 13]


## check possible dimensionality reduction

In [12]:
from sklearn.decomposition import PCA

In [13]:
pca= PCA(n_components=0.995, random_state=2308).fit(X_train)
pca.n_components_

74

Only a modest dimensionality reduction is possible using PCA

In [14]:
## Stratified CV spliter for survival analysis

In [15]:
from sklearn.model_selection import RepeatedStratifiedKFold, StratifiedKFold

In [114]:
w_fastcph=survhive.FastCPH(rng_seed=2401, layer_sizes=[4,4], verbose=1)
w_fastcph

FastCPH(rng_seed=2401, layer_sizes=[4, 4], tie_approximation='breslow', lambda_seq=[0.001, 0.0010249999999999999, 0.001050625, 0.0010768906249999997, 0.0011038128906249996, 0.0011314082128906244, 0.00115969341821289, 0.0011886857536682123, 0.0012184028975099172, 0.0012488629699476653, 0.0012800845441963567, 0.0013120866578012656, 0.0013448888242462971, 0.0013785110448524542, 0.0014129738209737656, 0.0014482981664981096, 0.0014845056206605623, 0.001521618261177076, 0.001559658717706503, 0.0015986501856491654, 0.0016386164402903943, 0.0016795818512976542, 0.0017215713975800952, 0.0017646106825195975, 0.0018087259495825872, 0.0018539440983221518, 0.0019002927007802054, 0.0019478000182997105, 0.001996495018757203, 0.002046407394226133, 0.002097567579081786, 0.0021500067685588306, 0.002203756937772801, 0.0022588508612171212, 0.0023153221327475485, 0.0023732051860662373, 0.002432535315717893, 0.00249334869861084, 0.002555682416076111, 0.0026195744764780132, 0.0026850638383899635, 0.0027521904343497123, 0.0028209951952084546, 0.002891520075088666, 0.0029638080769658825, 0.0030379032788900293, 0.0031138508608622795, 0.0031916971323838364, 0.003271489560693432, 0.0033532767997107677, 0.0034371087197035363, 0.003523036437696125, 0.0036111123486385274, 0.0037013901573544903, 0.0037939249112883522, 0.003888773034070561, 0.003985992359922324, 0.004085642168920382, 0.004187783223143391, 0.0042924778037219755, 0.004399789748815024, 0.0045097844925354, 0.004622529104848784, 0.004738092332470004, 0.004856544640781753, 0.004977958256801297, 0.005102407213221329, 0.0052299673935518615, 0.005360716578390657, 0.005494734492850423, 0.005632102855171683, 0.005772905426550975, 0.005917228062214749, 0.006065158763770117, 0.0062167877328643695, 0.006372207426185978, 0.006531512611840627, 0.006694800427136643, 0.006862170437815058, 0.007033724698760434, 0.007209567816229444, 0.00738980701163518, 0.007574552186926058, 0.007763915991599209, 0.007958013891389188, 0.008156964238673917, 0.008360888344640766, 0.008569910553256782, 0.008784158317088201, 0.009003762275015407, 0.009228856331890791, 0.00945957774018806, 0.00969606718369276, 0.009938468863285078, 0.010186930584867204, 0.010441603849488884, 0.010702643945726105, 0.010970210044369256, 0.011244465295478486, 0.011525576927865449, 0.011813716351062082, 0.012109059259838635, 0.0124117857413346, 0.012722080384867962, 0.01304013239448966, 0.013366135704351901, 0.013700289096960697, 0.014042796324384713, 0.014393866232494331, 0.014753712888306687, 0.015122555710514353, 0.01550061960327721, 0.01588813509335914, 0.016285338470693116, 0.016692471932460443, 0.017109783730771953, 0.017537528324041252, 0.01797596653214228, 0.018425365695445835, 0.018885999837831978, 0.019358149833777778, 0.019842103579622218, 0.020338156169112772, 0.02084661007334059, 0.021367775325174105, 0.021901969708303454, 0.02244951895101104, 0.023010756924786314, 0.023586025847905968, 0.024175676494103616, 0.0247800684064562, 0.025399570116617608, 0.026034559369533045, 0.02668542335377137, 0.02735255893761565, 0.02803637291105604, 0.02873728223383244, 0.029455714289678244, 0.0301921071469202, 0.030946909825593203, 0.03172058257123303, 0.03251359713551385, 0.0333264370639017, 0.03415959799049924, 0.035013587940261715, 0.035888927638768255, 0.03678615082973745, 0.03770580460048089, 0.03864844971549291, 0.039614660958380225, 0.04060502748233973, 0.04162015316939822, 0.042660656998633174, 0.043727173423599, 0.04482035275918896, 0.045940861578168686, 0.0470893831176229, 0.04826661769556347, 0.04947328313795255, 0.05071011521640136, 0.051977868096811396, 0.053277314799231666, 0.054609247669212456, 0.05597447886094276, 0.05737384083246633, 0.05880818685327798, 0.060278391524609926, 0.06178535131272517, 0.0633299850955433, 0.06491323472293187, 0.06653606559100515, 0.06819946723078028, 0.06990445391154979, 0.07165206525933851, 0.07344336689082198, 0.07527945106309253, 0.07716143733966983, 0.07909047327316157, 0.0810677351049906, 0.0830944284826153

In [115]:
w_lasso=w_fastcph.fit(X_train, y_train)

epoch: 0
loss: 4.988934516906738
epoch: 1
loss: 4.967841148376465
epoch: 2
loss: 4.947465896606445
epoch: 3
loss: 4.927479267120361
epoch: 4
loss: 4.907822132110596
epoch: 5
loss: 4.888700485229492
epoch: 6
loss: 4.87002420425415
epoch: 7
loss: 4.851817607879639
epoch: 8
loss: 4.834465980529785
epoch: 9
loss: 4.817636013031006
epoch: 10
loss: 4.801114082336426
epoch: 11
loss: 4.784931182861328
epoch: 12
loss: 4.769046306610107
epoch: 13
loss: 4.7536845207214355
epoch: 14
loss: 4.739511489868164
epoch: 15
loss: 4.725949287414551
epoch: 16
loss: 4.712684154510498
epoch: 17
loss: 4.699960231781006
epoch: 18
loss: 4.687402725219727
epoch: 19
loss: 4.674999237060547
epoch: 20
loss: 4.662703990936279
epoch: 21
loss: 4.650566577911377
epoch: 22
loss: 4.63859224319458
epoch: 23
loss: 4.626996040344238
epoch: 24
loss: 4.6154656410217285
epoch: 25
loss: 4.603992938995361
epoch: 26
loss: 4.592909336090088
epoch: 27
loss: 4.582374572753906
epoch: 28
loss: 4.572081089019775
epoch: 29
loss: 4.561834

In [116]:
w_lasso.fit_lambda_

0.003523036437696125

In [117]:
w_lasso.predict(X_test)

array([ -9.345862  ,  -7.1754155 , -24.634806  ,  -7.1119146 ,
        -2.4740973 , -24.452074  , -24.44435   , -13.838684  ,
        -1.7425482 , -21.197063  , -18.61378   , -10.23551   ,
         0.46123374, -11.6502495 , -16.697102  ,  -8.088986  ,
        -6.4313602 ,  -0.7819879 ,  -8.450064  , -18.331095  ,
       -20.881905  , -25.489023  , -11.401772  , -10.583445  ,
        -8.251638  ,   4.3901577 ,  -5.185144  , -22.502214  ,
        -3.3516102 ,  -9.552089  ,   0.52958584, -16.273197  ,
        -4.147382  ,   0.46969783, -27.83774   , -27.202974  ,
       -11.805508  ,  -3.069765  ,  14.027991  , -22.521828  ,
        -7.019005  , -16.55804   , -23.008898  ,  -6.505207  ,
       -16.505173  ,  -1.6809804 , -24.238497  ,  -2.6657643 ,
        -7.6268926 ,  -7.7024508 ], dtype=float32)

In [118]:
w_lasso.score(X_train, y_train), w_lasso.score(X_test,y_test)

(0.9995648389904265, 0.6018099547511312)

In [119]:
#survhive.get_time(y_train)
median_time = numpy.median(survhive.get_time(y_train))
times =[ median_time, median_time/2, median_time*2]
times

[4339.5, 2169.75, 8679.0]

In [120]:
w_steps = w_lasso.predict_survival(X_train[4:5], times)

In [121]:
w_steps

array([[6.87416170e+04, 1.38645206e-01, 2.43241167e+06]])

In [122]:
scorer = survhive.metrics.make_time_dependent_scorer(
            survhive.metrics.neg_brier_score,
            time_mode="quantiles",
            time_values=[0.1, 0.25, 0.4, 0.5, 0.6, 0.75],
        )


In [123]:
scorer(w_lasso, X_train, y_train), scorer(w_lasso, X_test, y_test)

/usr/local/ivan/Unito/conda/envs/fastcph/lib/python3.8/site-packages/sksurv/linear_model/coxph.py:124: RuntimeWarning: overflow encountered in power
  funcs[i] = StepFunction(x=self.baseline_survival_.x, y=np.power(self.baseline_survival_.y, risk_score[i]))
/usr/local/ivan/Unito/conda/envs/fastcph/lib/python3.8/site-packages/sksurv/linear_model/coxph.py:124: RuntimeWarning: overflow encountered in power
  funcs[i] = StepFunction(x=self.baseline_survival_.x, y=np.power(self.baseline_survival_.y, risk_score[i]))
/usr/local/ivan/Unito/survhive/survhive/metrics.py:96: RuntimeWarning: overflow encountered in square
  return -numpy.square(err).mean()


(-0.004527416573666531, -inf)

In [124]:
w_breslow = w_lasso.breslow_estimator_.get_survival_function(w_lasso.predict(X_train[4:6]))
w_breslow

array([StepFunction(x=array([ 269.,  289.,  394.,  404.,  421.,  434.,  530.,  649.,  690.,
               723.,  730.,  794.,  880.,  910.,  958.,  994., 1023., 1112.,
              1136., 1171., 1206., 1215., 1259., 1290., 1554., 1591., 1598.,
              1693., 1703., 1721., 1731., 1742., 1743., 1781., 1815., 2105.,
              2196., 2225., 2349., 2454., 2549., 2561., 2604., 2647., 2672.,
              2892., 2909., 2965., 2972., 3121., 3188., 3296., 3311., 3313.,
              3492., 3544., 3555., 3614., 3721., 3771., 3800., 3822., 3900.,
              3914., 3976., 4052., 4066., 4085., 4178., 4181., 4227., 4279.,
              4297., 4327., 4352., 4353., 4415., 4472., 4487., 4537., 4555.,
              4596., 4603., 4642., 4652., 4672., 4675., 4681., 4691., 4791.,
              4830., 4857., 4863., 4866., 4925., 4952., 4980., 5012., 5014.,
              5035., 5110., 5181., 5228., 5238., 5306., 5316., 5379., 5519.,
              5533., 5571., 5602., 5612., 5651., 5653., 5661.

In [36]:
r= numpy.array(
    [ numpy.interp( _t, p.x, p.y, left=1.0 ) for _t in [median_time, median_time/2]  for p in w_breslow]
)
r

array([0.        , 0.        , 0.39113534, 1.        ])

----

## Test with CV-based lambda selection

In [ ]:
cv_set=survhive.survival_crossval_splitter(X_train,y_train,
                                           n_splits=3,
                                           n_repeats=1,
                                           rng_seed=seed)
cv_set

In [ ]:
fastcph.get_params(deep=True)

In [ ]:
fastcph_cv=lassonet.LassoNetCoxRegressorCV(cv=cv_set,
                                          hidden_dims=(8,8),
                                          tie_approximation='breslow',
                                          path_multiplier=1.02,
                                           backtrack=True,
                                          torch_seed=seed,random_state=seed)
fastcph_cv

In [ ]:
fastcph_cv.fit(X_train,yup)

In [ ]:
fastcph_cv.best_cv_scores_, fastcph_cv.best_lambda_, fastcph_cv.best_cv_score_, fastcph_cv.best_selected_


In [ ]:
fastcph_cv.score(X_test,yup_test)

In [ ]:
fastcph_cv.path_

In [ ]:
fastch_cv.path_

In [ ]:
#fitted_fastcph.path_.loss , fitted_fastcph.path_.lambda 

lambda_cv_min = min(fastcph_cv.path_, key=(lambda x: x.objective))
#lambda_min = min([(_.objective, _.lambda_)  for _ in fitted_fastcph.path_])
lambda_cv_min


In [ ]:
fastcph.set_params(lambda_seq=[lambda_cv_min.lambda_],
                   random_state=seed,torch_seed=seed,
                   verbose=1)
refit_fastcph_cv=fastcph.fit(X_train,yup)

In [ ]:
refit_fastcph_cv.predict(X_test)

In [ ]:
refit_fastcph_cv.score(X_test,yup_test)